Repository nurfachmi/perpustakaan, pull requests merged in 2023-10, with the labels that each got.

#1 Manajemen Buku pada Role Pustakawan
  app/Http/Controllers/BookController.php
  app/Http/Controllers/Datatables/BookDatatables.php
  app/Models/Book.php
  app/Models/Category.php
  database/migrations/2023_10_01_224407_create_categories_table.php
  database/migrations/2023_10_01_224919_create_books_table.php
  database/seeders/BookSeeder.php
  database/seeders/CategorySeeder.php
  database/seeders/DatabaseSeeder.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/menu.blade.php
  resources/views/pages/book/create.blade.php
  resources/views/pages/book/edit.blade.php
  resources/views/pages/book/index.blade.php
  routes/datatables.php
  routes/web.php
Labels: enhancement, hacktoberfest-accepted

#2 Peminjaman Buku
  app/Http/Controllers/BorrowBookController.php
  app/Http/Controllers/BorrowController.php
  app/Http/Controllers/Datatables/BorrowBookDatatables.php
  app/Http/Controllers/Datatables/BorrowDatatables.php
  app/Http/Requests/BorrowDestroyRequest.php
  app/Http/Requests/BorrowStoreRequest.php
  app/Http/Requests/BorrowUpdateRequest.php
  app/Models/Borrow.php
  app/Models/BorrowBook.php
  app/Models/User.php
  config/perpustakaan.php
  database/migrations/2023_10_02_200305_create_borrows_table.php
  database/migrations/2023_10_02_201108_create_borrow_books_table.php
  database/seeders/PermissionSeeder.php
  database/seeders/Permissions/BorrowPermission.php
  resources/views/layouts/menu.blade.php
  resources/views/pages/borrow/book/index.blade.php
  resources/views/pages/borrow/create.blade.php
  resources/views/pages/borrow/index.blade.php
  routes/datatables.php
  routes/web.php
Labels: enhancement, hacktoberfest-accepted

#3 refactor: peminjaman buku 📖
  app/Http/Controllers/BorrowBookController.php
  app/Http/Controllers/BorrowController.php
  app/Http/Controllers/Datatables/BorrowBookDatatables.php
  app/Http/Requests/BorrowBookStoreRequest.php
  app/Models/BorrowBook.php
  resources/views/pages/borrow/book/index.blade.php
Labels: enhancement, hacktoberfest-accepted

#4 docs: refresh fitur 🙊
  README.md
Labels: documentation

#9 Refactor Modul Buku dan Readme
  README.md
  app/Http/Controllers/BookController.php
  app/Http/Requests/BookStoreRequest.php
  app/Http/Requests/BookUpdateRequest.php
  app/Models/Book.php
  app/Traits/Randomizer.php
  database/migrations/2023_10_06_212602_add_some_columns_to_books_table.php
  resources/views/components/datatable-action.blade.php
  resources/views/pages/book/create.blade.php
  resources/views/pages/book/edit.blade.php
  resources/views/pages/book/index.blade.php
Labels: enhancement, hacktoberfest-accepted

#11 fix ISBN
  app/Http/Controllers/BookController.php
  app/Traits/Randomizer.php
  database/factories/BookFactory.php
  database/factories/CategoryFactory.php
  database/seeders/BookSeeder.php
  database/seeders/CategorySeeder.php
  resources/views/pages/book/create.blade.php
  resources/views/pages/book/edit.blade.php
Labels: enhancement

#10 docs: Cara menjalankan aplikasi
  Makefile
  README.md
  docker-compose.yml
Labels: enhancement, hacktoberfest-accepted

#16 Feature: event listener untuk handle input dari barcode scanner di halaman pinjam buku
  Makefile
  public/js/barcodescanner.js
  resources/views/pages/borrow/book/index.blade.php
Labels: enhancement, hacktoberfest-accepted
